version: '2'
services:
 zookeeper1:
   image: confluentinc/cp-zookeeper:latest
   environment:
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
   networks:
      - confluent

 kafka1:
   image: confluentinc/cp-kafka:latest
   depends_on:
     - zookeeper1
   ports:
     - 9092:9092
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_DEFAULT_REPLICATION_FACTOR: 1  
   networks:
      - confluent

 zookeeper2:
   image: confluentinc/cp-zookeeper:latest
   environment:
     ZOOKEEPER_CLIENT_PORT: 2182
     ZOOKEEPER_TICK_TIME: 2000
   networks:
      - confluent

 kafka2:
   image: confluentinc/cp-kafka:latest
   depends_on:
     - zookeeper2
   ports:
     - 9093:9092
   environment:
     KAFKA_BROKER_ID: 2
     KAFKA_ZOOKEEPER_CONNECT: zookeeper2:2182
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_DEFAULT_REPLICATION_FACTOR: 1
   networks:
      - confluent

 control-center:
   image: confluentinc/cp-enterprise-control-center:latest
   depends_on:
     - kafka1
     - kafka2
   ports:
     - 9021:9021
   environment:
     CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9092
     CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2182
     CONTROL_CENTER_REPLICATION_FACTOR: 1
   networks:
      - confluent

networks:
  confluent:
